### ISSUE TITLE
Custom Gif not showing 

### ISSUE THREAD

**Issue by SheepDomination** [hoovercj/vscode-power-mode#63]
I'm attempting to use my own custom animated gif but when adding it to my workspace settings; nothing appears ?
```
"powermode.customExplosions": [
            "https://~~~~"
        ],
        "powermode.customCss": {
            "background-color": "#FFBA10;",
            "z-index": 2,
            "left": "-25px",
            "background-blend-mode:": "multiply"
        },
```

**Comment by jennatollerson** [comment]
Same. It worked this time last year, but at some point my custom animated gif stopped showing up.

**Comment by hoovercj** [comment]
@SheepDomination @jennatollerson apologies for not getting back to you sooner.

I've confirmed that local files no longer work due to a more restrictive security policy in the underlying Chrome engine that VS Code uses, but I am able to use GIFs. 

Specifically, this worked for me:

```
    "powermode.customExplosions": [
        "https://media.giphy.com/media/sLMRyFR4eIEgnFe4mK/giphy.gif"
    ]
```

If you're interested in helping to resolve the issue, you can either:
1. Share the url that isn't working
2. Press "ctrl+shift+i" to open the devtools in VS Code and look in the console output as you try to type? If it can't load the image, I would expect to see something like this, or I would expect there to be some other error output that would help me understand the issue.

<img width="203" alt="image" src="https://user-images.githubusercontent.com/2957173/155874489-274b9994-9bfb-4a19-8cdd-6038426c6633.png">

**Comment by jennatollerson** [comment]
Hi there! I ultimately solved this for myself by converting my local image to a Base64 data url and using that instead, i.e. `"powermode.customExplosions": ["data:image/gif;base64,lotsoftext"]`

I thought I had come back here and shared that solution but clearly I had not. 😬 Thank you for following up on this issue though! Love my sparkling type. 😁
